catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - vite@6.4.1
  - semver@6.3.1

packages:
  - apps/**
  - packages/**

catalogs:
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@eslint-react/eslint-plugin': ^2.8.1
    eslint: ^9.39.2
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-format: ^1.3.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    turbo: ^2.8.0
  prod:
    '@tailwindcss/vite': ^4.1.18
    astro: ^5.17.1
    tailwindcss: ^4.1.18
