catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1

packages:
  - apps/**
  - packages/**

catalogs:
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@cloudflare/vite-plugin': ^1.22.1
    '@eslint-react/eslint-plugin': ^2.8.1
    '@total-typescript/tsconfig': ^1.0.4
    '@types/node': ^25.1.0
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^5.1.2
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    turbo: ^2.8.0
    typescript: ^5.9.3
    vite: ^7.3.1
    vite-tsconfig-paths: ^6.0.5
    wrangler: ^4.61.1
  prod:
    '@hugeicons-pro/core-stroke-rounded': ^3.1.0
    '@hugeicons/react': ^1.1.4
    '@tailwindcss/vite': ^4.1.18
    '@tanstack/react-router': ^1.157.16
    '@tanstack/react-start': ^1.157.16
    clsx: ^2.1.1
    motion: ^12.29.2
    react: ^19.2.4
    react-aria-components: ^1.14.0
    react-dom: ^19.2.4
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.18
    zod: ^4.3.6
